---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway-consul
spec:
  destination:
    name: consul-ui
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: TCPRoute
metadata:
  name: route-consul
  namespace: consul
spec:
  parentRefs:
  - name: api-gateway
    namespace: consul
  rules:
  - matches:
    - path:
        type: Exact
        value: /consul
    backendRefs:
    - kind: Service
      name: consul-ui
      namespace: consul
      port: 80
