global:
  datacenter: "dc1"
  name: consul
  domain: consul
  secretsBackend:
    vault:
      enabled: true
      consulServerRole: consul-server
      consulCARole: consul-ca
      connectCA:
        rootPKIPath: connect-root
        intermediatePKIPath: connect-intermediate-dc1
        address: https://vault.vault.svc:8200
        additionalConfig: |
          { "connect": [{ "ca_provider": "vault", "enabled": true}] }
      ca:
        secretName: vault-crt
        secretKey: vault.crt
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: pki/cert/ca
  federation:
    enabled: false
    createFederationSecret: false
  acls:
    manageSystemACLs: false
  gossipEncryption:
    secretName: consul/data/secret/gossip
    secretKey: gossip
server:
  replicas: 1
  exposeGossipAndRPCPorts: true
  serverCert:
    secretName: pki/issue/consul-server
connectInject:
  replicas: 1
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true
  apiGateway: 
    managedGatewayClass:
      serviceType: LoadBalancer
prometheus:
  enabled: true
ui:
  enabled: true
  service:
    nodePort:
      http:  80
  metrics:
    provider: prometheus
    baseURL: http://prometheus-server
syncCatalog:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
  k8sDenyNamespaces: ["kube-system", "kube-public", "consul"]
